/**
 * generated by Xtext 2.36.0
 */
package gameOfLife.model.validation;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class GDSLValidator extends AbstractGDSLValidator {
}
