/*
 * generated by Xtext 2.36.0
 */
package gameOfLife.model.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import gameOfLife.model.ide.contentassist.antlr.internal.InternalGDSLParser;
import gameOfLife.model.services.GDSLGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class GDSLParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(GDSLGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, GDSLGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getCellStateAccess().getAlternatives(), "rule__CellState__Alternatives");
			builder.put(grammarAccess.getRelationalOperatorAccess().getAlternatives(), "rule__RelationalOperator__Alternatives");
			builder.put(grammarAccess.getActionAccess().getAlternatives(), "rule__Action__Alternatives");
			builder.put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
			builder.put(grammarAccess.getGridAccess().getGroup(), "rule__Grid__Group__0");
			builder.put(grammarAccess.getGridAccess().getGroup_2(), "rule__Grid__Group_2__0");
			builder.put(grammarAccess.getRangeAccess().getGroup(), "rule__Range__Group__0");
			builder.put(grammarAccess.getRuleAccess().getGroup(), "rule__Rule__Group__0");
			builder.put(grammarAccess.getConditionAccess().getGroup(), "rule__Condition__Group__0");
			builder.put(grammarAccess.getModelAccess().getGridAssignment_0(), "rule__Model__GridAssignment_0");
			builder.put(grammarAccess.getModelAccess().getRulesAssignment_1(), "rule__Model__RulesAssignment_1");
			builder.put(grammarAccess.getGridAccess().getRangesAssignment_1(), "rule__Grid__RangesAssignment_1");
			builder.put(grammarAccess.getGridAccess().getRangesAssignment_2_1(), "rule__Grid__RangesAssignment_2_1");
			builder.put(grammarAccess.getRangeAccess().getStartAssignment_0(), "rule__Range__StartAssignment_0");
			builder.put(grammarAccess.getRangeAccess().getEndAssignment_2(), "rule__Range__EndAssignment_2");
			builder.put(grammarAccess.getRuleAccess().getStateAssignment_0(), "rule__Rule__StateAssignment_0");
			builder.put(grammarAccess.getRuleAccess().getConditionAssignment_2(), "rule__Rule__ConditionAssignment_2");
			builder.put(grammarAccess.getRuleAccess().getActionAssignment_4(), "rule__Rule__ActionAssignment_4");
			builder.put(grammarAccess.getConditionAccess().getOperatorAssignment_0(), "rule__Condition__OperatorAssignment_0");
			builder.put(grammarAccess.getConditionAccess().getValueAssignment_1(), "rule__Condition__ValueAssignment_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private GDSLGrammarAccess grammarAccess;

	@Override
	protected InternalGDSLParser createParser() {
		InternalGDSLParser result = new InternalGDSLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public GDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
