/*
 * generated by Xtext 2.36.0
 */
package gameOfLife.model.ui.tests;

import com.google.inject.Injector;
import gameOfLife.gdsl.ui.internal.GdslActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class GDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return GdslActivator.getInstance().getInjector("gameOfLife.model.GDSL");
	}

}
