/**
 * generated by Xtext 2.36.0
 */
package gameOfLife.model.gDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Grid</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link gameOfLife.model.gDSL.Grid#getRanges <em>Ranges</em>}</li>
 * </ul>
 *
 * @see gameOfLife.model.gDSL.GDSLPackage#getGrid()
 * @model
 * @generated
 */
public interface Grid extends EObject
{
  /**
   * Returns the value of the '<em><b>Ranges</b></em>' containment reference list.
   * The list contents are of type {@link gameOfLife.model.gDSL.Range}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ranges</em>' containment reference list.
   * @see gameOfLife.model.gDSL.GDSLPackage#getGrid_Ranges()
   * @model containment="true"
   * @generated
   */
  EList<Range> getRanges();

} // Grid
