/**
 * generated by Xtext 2.36.0
 */
package gameOfLife.model.gDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link gameOfLife.model.gDSL.Rule#getState <em>State</em>}</li>
 *   <li>{@link gameOfLife.model.gDSL.Rule#getCondition <em>Condition</em>}</li>
 *   <li>{@link gameOfLife.model.gDSL.Rule#getAction <em>Action</em>}</li>
 * </ul>
 *
 * @see gameOfLife.model.gDSL.GDSLPackage#getRule()
 * @model
 * @generated
 */
public interface Rule extends EObject
{
  /**
   * Returns the value of the '<em><b>State</b></em>' attribute.
   * The literals are from the enumeration {@link gameOfLife.model.gDSL.CellState}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>State</em>' attribute.
   * @see gameOfLife.model.gDSL.CellState
   * @see #setState(CellState)
   * @see gameOfLife.model.gDSL.GDSLPackage#getRule_State()
   * @model
   * @generated
   */
  CellState getState();

  /**
   * Sets the value of the '{@link gameOfLife.model.gDSL.Rule#getState <em>State</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>State</em>' attribute.
   * @see gameOfLife.model.gDSL.CellState
   * @see #getState()
   * @generated
   */
  void setState(CellState value);

  /**
   * Returns the value of the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' containment reference.
   * @see #setCondition(Condition)
   * @see gameOfLife.model.gDSL.GDSLPackage#getRule_Condition()
   * @model containment="true"
   * @generated
   */
  Condition getCondition();

  /**
   * Sets the value of the '{@link gameOfLife.model.gDSL.Rule#getCondition <em>Condition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition</em>' containment reference.
   * @see #getCondition()
   * @generated
   */
  void setCondition(Condition value);

  /**
   * Returns the value of the '<em><b>Action</b></em>' attribute.
   * The literals are from the enumeration {@link gameOfLife.model.gDSL.Action}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Action</em>' attribute.
   * @see gameOfLife.model.gDSL.Action
   * @see #setAction(Action)
   * @see gameOfLife.model.gDSL.GDSLPackage#getRule_Action()
   * @model
   * @generated
   */
  Action getAction();

  /**
   * Sets the value of the '{@link gameOfLife.model.gDSL.Rule#getAction <em>Action</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Action</em>' attribute.
   * @see gameOfLife.model.gDSL.Action
   * @see #getAction()
   * @generated
   */
  void setAction(Action value);

} // Rule
