/**
 * generated by Xtext 2.36.0
 */
package gameOfLife.model.ui.contentassist;

/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class GDSLProposalProvider extends AbstractGDSLProposalProvider {
}
