/**
 * generated by Xtext 2.36.0
 */
package gameOfLife.model.generator;

import com.google.common.collect.Iterators;
import gameOfLife.model.gDSL.Model;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.IteratorExtensions;

@SuppressWarnings("all")
public class GDSLGenerator extends AbstractGenerator {
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    final Model root = IteratorExtensions.<Model>head(Iterators.<Model>filter(resource.getAllContents(), Model.class));
    if ((root != null)) {
      fsa.generateFile("RulesOfLife.java", TextGenerator.toText(root));
    }
  }
}
