/*
 * generated by Xtext 2.36.0
 */
package gameOfLife.model.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractGDSLScopeProvider extends DelegatingScopeProvider {
}
