/**
 * generated by Xtext 2.36.0
 */
package gameOfLife.model.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
@SuppressWarnings("all")
public class GDSLQuickfixProvider extends DefaultQuickfixProvider {
}
