/**
 * generated by Xtext 2.36.0
 */
package gameOfLife.model.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import gameOfLife.model.GDSLRuntimeModule;
import gameOfLife.model.GDSLStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class GDSLIdeSetup extends GDSLStandaloneSetup {
  @Override
  public Injector createInjector() {
    GDSLRuntimeModule _gDSLRuntimeModule = new GDSLRuntimeModule();
    GDSLIdeModule _gDSLIdeModule = new GDSLIdeModule();
    return Guice.createInjector(Modules2.mixin(_gDSLRuntimeModule, _gDSLIdeModule));
  }
}
