/*
 * generated by Xtext 2.36.0
 */
package gameOfLife.model


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class GDSLRuntimeModule extends AbstractGDSLRuntimeModule {
}
